
//----------------------------------------------------
// The following code was generated by CUP v0.10a
// Wed Jul 24 21:44:00 EDT 1996
//----------------------------------------------------

package Parse;

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int AUTO = 0;
  static final int BREAK = 1;
  static final int CASE = 2;
  static final int CHAR = 3;
  static final int CONST = 4;
  static final int CONTINUE = 5;
  static final int DEFAULT = 6;
  static final int DO = 7;
  static final int ELSE = 8;
  static final int ENUM = 9;
  static final int EXTERN = 10;
  static final int FOR = 11;
  static final int GOTO = 12;
  static final int IF = 13;
  static final int INT = 14;
  static final int LONG = 15;
  static final int REGISTER = 16;
  static final int RETURN = 17;
  static final int SHORT = 18;
  static final int SIGNED = 19;
  static final int SIZEOF = 20;
  static final int STATIC = 21;
  static final int STRUCT = 22;
  static final int SWITCH = 23;
  static final int TYPEDEF = 24;
  static final int UNION = 25;
  static final int UNSIGNED = 26;
  static final int VOID = 27;
  static final int VOLATILE = 28;
  static final int WHILE = 29;
  static final int VAR = 30;
  static final int FUN = 31;
  static final int PLUS = 32;
  static final int MINUS = 33;
  static final int TIMES = 34;
  static final int DIVIDE = 35;
  static final int MOD = 36;
  static final int INC = 37;
  static final int DEC = 38;
  static final int ASSIGN = 39;
  static final int EQ = 40;
  static final int NEQ = 41;
  static final int LT = 42;
  static final int LE = 43;
  static final int GT = 44;
  static final int GE = 45;
  static final int ANDAND = 46;
  static final int OROR = 47;
  static final int NOT = 48;
  static final int BITAND = 49;
  static final int BITOR = 50;
  static final int BITXOR = 51;
  static final int BITNOT = 52;
  static final int LSHIFT = 53;
  static final int RSHIFT = 54;
  static final int SEMI = 55;
  static final int COMMA = 56;
  static final int DOT = 57;
  static final int COLON = 58;
  static final int QUESTION = 59;
  static final int LPAREN = 60;
  static final int RPAREN = 61;
  static final int LBRACK = 62;
  static final int RBRACK = 63;
  static final int LBRACE = 64;
  static final int RBRACE = 65;
  static final int ARROW = 66;
  static final int HASH = 67;
  static final int ID = 68;
  static final int DECIMAL_LITERAL = 69;
  static final int CHAR_LITERAL = 70;
  static final int STRING_LITERAL = 71;
  static final int EOF = 72;
};
